### ISSUE TITLE
KeyError: 'gpio'

### ISSUE THREAD

**Issue by Pickles726** [peckrob/petfeedd#7]
Hello,

I have just installed the Docker version and I'm getting the error below:
192.168.0.100 - - [13/Aug/2019 07:53:04] "GET /api/status HTTP/1.1" 200 -
petfeedd 2019-08-13 07:53:07,158 (INFO): Found a feed event. Dispensing 1 feeds.
192.168.0.100 - - [13/Aug/2019 07:53:07] "POST /api/feed HTTP/1.1" 200 -
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 68, in feed
    feed_size_time = float(self.config["gpio"]["servo_feed_time"]) * float(feed_size)
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'gpio'

Prior to installing and running this, I did an apt-get update and apt-get upgrade.

**Comment by peckrob** [comment]
Hi, I just tested this locally and everything looks okay. What docker command are you using to run petfeedd?

**Comment by Pickles726** [comment]
I was running the following command:
docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 8080 peckrob/petfeedd-arm32v7

I am able to hit the web page and view the database entries, but pressing the feed now button pops that stack. I am using an older Raspbian(Jessie). Perhaps that is the issue?

**Comment by peckrob** [comment]
Well, that looks right. Does `/etc/petfeedd.conf` contain the gpio section?

**Comment by Pickles726** [comment]
Yes, it has:
[gpio]
servo_pin=17
servo_feed_time=0.26

**Comment by peckrob** [comment]
Okay, let me go dig up a spare Pi and try it on actual hardware.

**Comment by Pickles726** [comment]
I am going to flash Buster onto another SD card and give that a go as well. I'll report back once I get everything set up.

**Comment by Pickles726** [comment]
Quick update: I have a running copy of Raspbian Buster installed. I am running into the same error.

**Comment by peckrob** [comment]
Okay, we had a storm last night and I lost electric power so I went to bed. I'll try to work through it tonight after work.

**Comment by peckrob** [comment]
So this is bizarre. I did a fresh install of Raspbian on a card, installed docker, pulled in petfeedd 0.2.1 and ran it on physical hardware. Copied the config file to `/etc/petfeedd.conf` and ran your command. Everything worked as expected.

I believe you that it is happening. Seems like there was someone in my comments was reporting a similar or identical issue, so I would like to research it some more. But the only thing that I know of that could cause that error is if the config file (or env variables) are not available.

You might try starting petfeedd in docker, then shelling into it (`docker exec -it <name> /bin/bash`) and see if the petfeedd.conf file looks okay inside the image.

If that doesn't work, can you make an image copy of your SD card and put it somewhere I could download it? I'll be happy to look inside and see if I can figure out what is going on. Either there's a bug or I need to update documentation. :)

**Comment by drewklein20** [comment]
I have this same error. Here is the full traceback:
petfeedd 2019-08-17 02:48:14,406 (INFO): Found a feed event. Dispensing 1 feeds.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 68, in feed
    feed_size_time = float(self.config["gpio"]["servo_feed_time"]) * float(feed_size)
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'gpio'

**Comment by peckrob** [comment]
Can you try shelling into the docker container and seeing if the config file looks correct?

**Comment by drewklein20** [comment]
My config is the example file renamed to petfeedd.conf in /etc/ directory. However, I'm initializing docker with the following command 

`docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7`

If I try to initialize it with the command below, my page does not load.

`docker run  --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7`

**Comment by peckrob** [comment]
Awesome, that one I think I know what it is. The default `bind_address` for web is `127.0.0.1` in the example config, so docker's networking won't be able to  see it. Try changing that to `0.0.0.0` in the config file and see if you can see the page.

**Comment by drewklein20** [comment]
Okay, so changing the bind address to 0.0.0.0 worked with the command below for accessing the webpage. But not this is the output I get when I try to run the feed now button. I have tested the servo with the test script in your documentation. Am I missing a dependency? I noticed that when I try to install python3-gpio it says package not found. However, I can still run the test script that uses python gpio.


docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7
Config file found at ./petfeedd.conf
Parsing configuration.
petfeedd 2019-08-17 15:16:45,324 (INFO): Logging enabled.
petfeedd 2019-08-17 15:16:45,330 (INFO): Starting web worker.
petfeedd 2019-08-17 15:16:45,335 (INFO): Starting time worker.
petfeedd 2019-08-17 15:16:45,338 (INFO): Starting notification worker.
petfeedd 2019-08-17 15:16:45,339 (INFO): Starting feed worker.
petfeedd 2019-08-17 15:16:45,363 (INFO): Starting auto discovery worker.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
172.17.0.1 - - [17/Aug/2019 15:16:51] "POST /api/feed HTTP/1.1" 200 -
petfeedd 2019-08-17 15:16:51,590 (INFO): Found a feed event. Dispensing 1 feeds.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 71, in pin
    pin = self.pins[n]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 863, in from_revision
    }[revcode_type]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 69, in feed
    servo = Servo(int(self.config["gpio"]["servo_pin"]))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 1012, in __init__
    pin, frequency=int(1 / frame_width), pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 327, in __init__
    pin, active_high, initial_value=None, pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 374, in __init__
    pin = self.pin_factory.pin(pin)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 73, in pin
    pin = self.pin_class(self, n)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/rpigpio.py", line 94, in __init__
    super(RPiGPIOPin, self).__init__(factory, number)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 241, in __init__
    factory.pi_info.physical_pin(repr(self))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/__init__.py", line 130, in <lambda>
    lambda self: self._get_pi_info(),
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 90, in _get_pi_info
    self._info = pi_info(self._get_revision())
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 1156, in pi_info
    return PiBoardInfo.from_revision(revision)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 957, in from_revision
    raise PinUnknownPi('unable to parse new-style revision "%x"' % revision)
gpiozero.exc.PinUnknownPi: unable to parse new-style revision "c03111"

172.17.0.1 - - [17/Aug/2019 15:16:51] "GET /api/events HTTP/1.1" 200 -

**Comment by peckrob** [comment]
What hardware are you using?

**Comment by chifo1971** [comment]
Hello,
_I am having the same problem... When I run the docker using:_ 

> docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7

_and  I click the feed button I get this error message:_

petfeedd 2019-09-20 03:07:29,382 (INFO): Found a feed event. Dispensing 1 feeds.
172.17.0.1 - - [20/Sep/2019 03:07:29] "POST /api/feed HTTP/1.1" 200 -
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 68, in feed
    feed_size_time = float(self.config["gpio"]["servo_feed_time"]) * float(feed_size)
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'gpio'

_and when I use the config file this is what i get:_

pi@raspberrypi:~ $ docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7
Config file found at ./petfeedd.conf
Parsing configuration.
petfeedd 2019-09-20 03:14:05,389 (INFO): Logging enabled.
petfeedd 2019-09-20 03:14:05,419 (INFO): Starting web worker.
petfeedd 2019-09-20 03:14:05,429 (INFO): Starting time worker.
petfeedd 2019-09-20 03:14:05,432 (INFO): Starting notification worker.
petfeedd 2019-09-20 03:14:05,436 (INFO): Starting feed worker.
petfeedd 2019-09-20 03:14:05,440 (INFO): Starting auto discovery worker.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
172.17.0.1 - - [20/Sep/2019 03:14:18] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [20/Sep/2019 03:14:19] "GET /api/events HTTP/1.1" 200 -
172.17.0.1 - - [20/Sep/2019 03:14:19] "GET /api/status HTTP/1.1" 200 -
172.17.0.1 - - [20/Sep/2019 03:14:23] "POST /api/feed HTTP/1.1" 200 -
petfeedd 2019-09-20 03:14:23,653 (INFO): Found a feed event. Dispensing 1 feeds.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 71, in pin
    pin = self.pins[n]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 863, in from_revision
    }[revcode_type]
KeyError: 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 69, in feed
    servo = Servo(int(self.config["gpio"]["servo_pin"]))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 1012, in __init__
    pin, frequency=int(1 / frame_width), pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 327, in __init__
    pin, active_high, initial_value=None, pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/devices.py", line 374, in __init__
    pin = self.pin_factory.pin(pin)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 73, in pin
    pin = self.pin_class(self, n)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/rpigpio.py", line 94, in __init__
    super(RPiGPIOPin, self).__init__(factory, number)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 241, in __init__
    factory.pi_info.physical_pin(repr(self))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/__init__.py", line 130, in <lambda>
    lambda self: self._get_pi_info(),
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/pi.py", line 90, in _get_pi_info
    self._info = pi_info(self._get_revision())
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 1156, in pi_info
    return PiBoardInfo.from_revision(revision)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-packages/gpiozero/pins/data.py", line 957, in from_revision
    raise PinUnknownPi('unable to parse new-style revision "%x"' % revision)
gpiozero.exc.PinUnknownPi: unable to parse new-style revision "a020d3"

172.17.0.1 - - [20/Sep/2019 03:14:23] "GET /api/events HTTP/1.1" 200 -

**Comment by sfriziona** [comment]
Same problem here with a MG996R servo and Raspberry pi3 B+

Config file found at ./petfeedd.conf
Parsing configuration.
petfeedd 2019-10-05 16:06:51,472 (INFO): Logging enabled.
petfeedd 2019-10-05 16:06:51,480 (INFO): Starting web worker.
petfeedd 2019-10-05 16:06:51,492 (INFO): Starting time worker.
petfeedd 2019-10-05 16:06:51,508 (INFO): Starting notification worker.
petfeedd 2019-10-05 16:06:51,513 (INFO): Starting feed worker.
petfeedd 2019-10-05 16:06:51,519 (INFO): Starting auto discovery worker.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
192.168.11.98 - - [05/Oct/2019 16:07:02] "GET / HTTP/1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:02] "GET /static/styles/site.css HTTP/1.1"                                                                                                                                                                                                                                              200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/jquery.min.js HTTP                                                                                                                                                                                                                                             /1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/bootstrap.min.js H                                                                                                                                                                                                                                             TTP/1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/vue.min.js HTTP/1.                                                                                                                                                                                                                                             1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/vue-router.min.js                                                                                                                                                                                                                                              HTTP/1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/vue-resource.min.j                                                                                                                                                                                                                                             s HTTP/1.1" 304 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /static/scripts/app.js HTTP/1.1" 3                                                                                                                                                                                                                                             04 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /api/status HTTP/1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:03] "GET /api/events HTTP/1.1" 200 -
192.168.11.98 - - [05/Oct/2019 16:07:05] "POST /api/feed HTTP/1.1" 200 -
petfeedd 2019-10-05 16:07:05,546 (INFO): Found a feed event. Dispensing 1 feeds.
192.168.11.98 - - [05/Oct/2019 16:07:05] "GET /api/events HTTP/1.1" 200 -
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/pi.py", line 71, in pin
    pin = self.pins[n]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/data.py", line 863, in from_revision
    }[revcode_type]
KeyError: 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 69, in feed
    servo = Servo(int(self.config["gpio"]["servo_pin"]))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/output_devices.py", line 1012, in __init__
    pin, frequency=int(1 / frame_width), pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/output_devices.py", line 327, in __init__
    pin, active_high, initial_value=None, pin_factory=pin_factory
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/devices.py", line 374, in __init__
    pin = self.pin_factory.pin(pin)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/pi.py", line 73, in pin
    pin = self.pin_class(self, n)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/rpigpio.py", line 94, in __init__
    super(RPiGPIOPin, self).__init__(factory, number)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/pi.py", line 241, in __init__
    factory.pi_info.physical_pin(repr(self))
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/__init__.py", line 130, in <lambda>
    lambda self: self._get_pi_info(),
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/pi.py", line 90, in _get_pi_info
    self._info = pi_info(self._get_revision())
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/data.py", line 1156, in pi_info
    return PiBoardInfo.from_revision(revision)
  File "/root/.local/share/virtualenvs/petfeedd-cNmTM59x/lib/python3.7/site-pack                                                                                                                                                                                                                                             ages/gpiozero/pins/data.py", line 957, in from_revision
    raise PinUnknownPi('unable to parse new-style revision "%x"' % revision)
gpiozero.exc.PinUnknownPi: unable to parse new-style revision "a020d3"

**Comment by peckrob** [comment]
Hi folks, would it be possible for someone to make an image of their SD card? This is obviously an issue but I haven’t been able to reproduce.

**Comment by chifo1971** [comment]
Hi Rob,
Does it have to be a copy of the full SD Card? if yes is there a
recommended way to do it or just copy the content to a Google Drive and
share it with you?

Regards,
Cherif

**Comment by collinjamess** [comment]
I'm having the same issue. I'll upload an image of my SD card


`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 68, in feed
    feed_size_time = float(self.config["gpio"]["servo_feed_time"]) * float(feed_size)
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'gpio'`

**Comment by collinjamess** [comment]
I cloned my SD card and it came out to 60gb. If that's too much, let me know and I'll find a way to make it smaller. https://drive.google.com/file/d/1ks2_Fi82aFaqeKTKaHfE3GZX59ay_KJH/view?usp=sharing

**Comment by peckrob** [comment]
@collinjamess Awesome, thank you so much!

I have set it to download overnight. I'll look at it tomorrow and see if I can figure out what's going on.

**Comment by sfriziona** [comment]
[Here](https://drive.google.com/open?id=1hrsIp2-uGOVUjfNIv2wRripn2gRZ6u1F) , hope you can help.

**Comment by peckrob** [comment]
Okay, this is a real head scratcher. I am starting to think this may be hardware related somehow?

I downloaded @sfriziona's image, burned it to a card and (after resetting the password), ran it in a Raspberry Pi 3B 1.2 attached to an MG-360 servo (because that is what I had laying around).

* Red - Pin 4 (5V)
* Black - Pin 6 (Ground)
* White - Pin 11 (GPIO17)

Ran the docker command from `bash_history` in fact. Has worked every time.

Pretty confused by this.

**Comment by peckrob** [comment]
Okay, I have ordered a Raspberry Pi 3 Model B+ and a MG996R servo. I will try to reproduce this as closely as possible.

**Comment by chifo1971** [comment]
I am currently uploading the SD image and will share the link once i have
it.
I also am suing MG996R Servo Motor (
https://components101.com/motors/mg996r-servo-motor-datasheet).
When i run the test script that you have in the main blog it works fine.

from gpiozero import Servo
from time import sleep

servo = Servo(17)
while True:
    servo.min()
    sleep(1)
    servo.mid()
    sleep(1)
    servo.max()
    sleep(1)


[image: image.png]

**Comment by chifo1971** [comment]
Here is the link to sd IMAGE:
https://drive.google.com/open?id=15KFfMV-6aJT-RxBRN2ti-GLCaACGIHkk

**Comment by collinjamess** [comment]
I"m going to load this up on my RPi B 3 1.2 and see if it works on that

**Comment by collinjamess** [comment]
Still getting the same error on a B 3 1.2. Could you look over my installation steps beginning from a fresh install and see if I'm doing anything wrong? 

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade


curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
sudo groupadd docker
sudo gpasswd -a $USER docker
newgrp docker

docker pull peckrob/petfeedd-arm32v7:0.2.1
sudo touch /opt/petfeedd.db && sudo chown pi: /opt/petfeedd.db
docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7

Here's my command line output from after installing docker 
`pi@raspberrypi:~ $ docker pull peckrob/petfeedd-arm32v7:0.2.1


0.2.1: Pulling from peckrob/petfeedd-arm32v7
d9d6acb4f2f3: Pull complete                                                                        aaa7b6903fc6: Pull complete                                                                        2011a5c4d9cb: Pull complete                                                                        c86082f3b932: Pull complete                                                                        707e6dddd4d8: Pull complete                                                                        3e6c20943b77: Pull complete                                                                        9058fdbb3732: Pull complete                                                                        0205f4d7156f: Pull complete                                                                        78c775cd88d9: Pull complete                                                                        d5a2ec1c3c2d: Pull complete                                                                        454355ec6125: Pull complete                                                                        2b65c460cc16: Pull complete                                                                        Digest: sha256:dd74ab16c03829574cacf2e4b023accde7c37a582f4b85a38235c7bf071ce0fc                    Status: Downloaded newer image for peckrob/petfeedd-arm32v7:0.2.1
docker.io/peckrob/petfeedd-arm32v7:0.2.1
pi@raspberrypi:~ $
pi@raspberrypi:~ $
pi@raspberrypi:~ $ sudo touch /opt/petfeedd.db && sudo chown pi: /opt/petfeedd.db                  
pi@raspberrypi:~ $
pi@raspberrypi:~ $ docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7
No config file specified. Proceeding with defaults and environment.
petfeedd 2019-10-07 02:46:40,774 (INFO): Logging enabled.
petfeedd 2019-10-07 02:46:40,801 (INFO): Starting web worker.
petfeedd 2019-10-07 02:46:40,812 (INFO): Starting time worker.
petfeedd 2019-10-07 02:46:40,816 (INFO): Starting notification worker.
petfeedd 2019-10-07 02:46:40,819 (INFO): Starting feed worker.
petfeedd 2019-10-07 02:46:40,821 (INFO): Starting auto discovery worker.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
10.0.0.154 - - [07/Oct/2019 02:46:48] "GET / HTTP/1.1" 200 -
10.0.0.154 - - [07/Oct/2019 02:46:48] "GET /api/events HTTP/1.1" 200 -
10.0.0.154 - - [07/Oct/2019 02:46:48] "GET /api/status HTTP/1.1" 200 -
10.0.0.154 - - [07/Oct/2019 02:46:50] "POST /api/feed HTTP/1.1" 200 -
petfeedd 2019-10-07 02:46:50,253 (INFO): Found a feed event. Dispensing 1 feeds.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/petfeedd/src/feed_worker.py", line 50, in run
    self.feed(feed_event.size)
  File "/petfeedd/src/feed_worker.py", line 68, in feed
    feed_size_time = float(self.config["gpio"]["servo_feed_time"]) * float(feed_size)
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'gpio'

10.0.0.154 - - [07/Oct/2019 02:46:50] "GET /api/events HTTP/1.1" 200 -`

**Comment by peckrob** [comment]
Sorry it took me a few days to get back to this, my 3B arrived on Thursday but I was speaking at a conference on Friday and Saturday, so this is the first chance I have had to get back to this.

I have successfully reproduced the bug and will hopefully have a fix later today.

**Comment by chifo1971** [comment]
Great! I will check it once your release it... I am traveling next week and
would really need the pet feeder to work!

**Comment by sfriziona** [comment]
Brilliant, can’t wait for a fix... Thank you very much.

**Comment by peckrob** [comment]
I have pushed tag `0.2.2-beta1` to Docker Hub, which seems to resolve the issue on my test device. Pull this and see how it does for y'all.

`docker pull peckrob/petfeedd-arm32v7:0.2.2-beta1`
`docker run --privileged -v /opt/petfeedd.db:/petfeedd/petfeedd.db -v /etc/petfeedd.conf:/petfeedd/petfeedd.conf -p 0.0.0.0:8080:8080 peckrob/petfeedd-arm32v7:0.2.2-beta1`

**Comment by sfriziona** [comment]
0.2.2-beta1 works , I'll be doing more testing tomorrow.
Thanks...

**Comment by chifo1971** [comment]
Yup it works! Great job and thanks a lot!

**Comment by peckrob** [comment]
Awesome! That's great to hear, and thanks everyone for reporting this bug and working with me to get it resolved. I will roll this as an official 0.2.2 release later tonight, update the docs and Dockerhub with the `latest` tag for this release.

(This change, theoretically, should have added support for the RPI4, but that is wholly untested right now until I have some 4 hardware to play with.)
